'use strict';

// Regenerates template/pdf-data.js (a base64-embedded copy of the PDF) so the
// download asset is ALWAYS bundled into the Vercel serverless function via a
// static require — runtime fs reads of a dynamic path can be tree-shaken out.
//
// To swap the template: replace template/resume-template.pdf, then run
//   npm run setup:pdf
// and redeploy (git push).

const fs = require('fs');
const path = require('path');

const src = process.env.TEMPLATE_PDF_PATH || path.join(__dirname, '..', 'template', 'resume-template.pdf');
const out = path.join(__dirname, '..', 'template', 'pdf-data.js');

const buf = fs.readFileSync(src);
const b64 = buf.toString('base64');
const contents =
  "'use strict';\n" +
  '// GENERATED by scripts/embed-pdf.js — do not edit by hand.\n' +
  `// Source: ${path.basename(src)} (${buf.length} bytes)\n` +
  `module.exports = Buffer.from(\n  '${b64}',\n  'base64'\n);\n`;

fs.writeFileSync(out, contents);
console.log(`Embedded ${buf.length} bytes from ${src} -> ${out}`);
